name: CI/CD Pipeline

on:
  push:
    branches: ["*"]
  pull_request:
    branches: ["*"]

jobs:
  BuildandTest:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "18"

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test

  SnykSecurityScan:
    needs: BuildandTest
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Snyk CLI
        run: npm install -g snyk

      - name: Authenticate with Snyk
        run: snyk auth ${{ secrets.SNYK_API_TOKEN }}

      - name: Snyk Scan
        run: snyk test --json > snyk_report.json || true

      - name: Upload Snyk report
        if: always()
        uses: actions/upload-artifact@v2
        with:
          name: snyk-report
          path: snyk_report.json

      - name: Download Snyk report
        uses: actions/download-artifact@v2
        with:
          name: snyk-report
          path: snyk_report_download

  Dockerize:
    runs-on: ubuntu-latest
    needs: SnykSecurityScan
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker image
        run: docker build -t randula98/ctse-itemservice:latest .

      - name: Tag Docker image
        run: docker tag randula98/ctse-itemservice:latest randula98/ctse-itemservice:1.0.0

      - name: Push Docker image
        run: docker push randula98/ctse-itemservice:1.0.0

      - name: Run Docker container
        run: docker run -d --name ctse-itemservice -p 8080:8080 randula98/ctse-itemservice:1.0.0

  DeploytoAzureKS:
    runs-on: ubuntu-latest
    needs: Dockerize
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Azure CLI
        run: |
          curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash

      - name: Login to Azure
        uses: Azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
          enable-AzPSSession: true

      - name: Run Azure commands
        run: |
          az account show
          az group list

      - name: Set Azure subscription
        run: az account set --subscription ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Create Azure Container Registry
        run: az acr create --resource-group ${{ secrets.AZURE_RESOURCE_GROUP }} --name ${{ secrets.AZURE_ACR_NAME }} --sku Basic

      - name: Login to Azure Container Registry
        run: az acr login --name ${{ secrets.AZURE_ACR_NAME }}
          
      - name: Pull Docker image from Docker Hub
        run: docker pull randula98/ctse-itemservice:1.0.0
        
      - name: Tag Docker image
        run: docker tag randula98/ctse-itemservice:1.0.0 ${{ secrets.AZURE_ACR_NAME }}.azurecr.io/ctse-itemservice:1.0.0

      - name: Push Docker image to Azure Container Registry
        run: docker push ${{ secrets.AZURE_ACR_NAME }}.azurecr.io/ctse-itemservice:1.0.0

      - name: Create Azure Kubernetes Cluster
        run: az aks create --resource-group ${{ secrets.AZURE_RESOURCE_GROUP }} --name ${{ secrets.AZURE_AKS_NAME }} --node-count 1 --enable-addons monitoring --generate-ssh-keys

      - name: Get Azure Kubernetes Cluster credentials
        run: az aks get-credentials --resource-group ${{ secrets.AZURE_RESOURCE_GROUP }} --name ${{ secrets.AZURE_AKS_NAME }}

      - name: Deploy to Azure Kubernetes Cluster
        run: kubectl apply -f kubernetes/deployment.yaml

      - name: Expose service
        run: kubectl expose deployment item-service-deployment --type=LoadBalancer --port=8080 --target-port=8080

      - name: Get service IP
        run: kubectl get service item-service-deployment
