name: CI/CD Pipeline

on:
  push:
    branches: ["*"]
  pull_request:
    branches: ["*"]

jobs:
  BuildandTest:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "18"

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test

  SnykSecurityScan:
    needs: BuildandTest
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Snyk CLI
        run: npm install -g snyk

      - name: Authenticate with Snyk
        run: snyk auth ${{ secrets.SNYK_API_TOKEN }}

      - name: Snyk Scan
        run: snyk test --json > snyk_report.json || true

      - name: Upload Snyk report
        if: always()
        uses: actions/upload-artifact@v2
        with:
          name: snyk-report
          path: snyk_report.json

      - name: Download Snyk report
        uses: actions/download-artifact@v2
        with:
          name: snyk-report
          path: snyk_report_download

  Dockerize:
    runs-on: ubuntu-latest
    needs: SnykSecurityScan
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker image
        run: docker build -t randula98/ctse-itemservice:latest .

      - name: Tag Docker image
        run: docker tag randula98/ctse-itemservice:latest randula98/ctse-itemservice:1.0.0

      - name: Push Docker image
        run: docker push randula98/ctse-itemservice:1.0.0

      - name: Run Docker container
        run: docker run -d --name my-microservice -p 8080:8080 randula98/ctse-itemservice:1.0.0
